port: 3002
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: directory
  sslmode: disable
redis:
  addr: localhost:6379
  password: ""
  db: 0
kafka:
  enable: false
  brokers: ["localhost:9092"]
  topics: ["hros_directory_events"]
  group_id: "hros_directory_svc_group"
nats:
  addr: localhost:4222
