port: 3005
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: auth
  sslmode: disable
redis:
  addr: localhost:6379
  password: ""
  db: 0
kafka:
  enable: false
  brokers: ["localhost:9092"]
  topic: "hros_admin_svc"
  group_id: "hros_admin_svc_group"
nats:
  addr: localhost:4222
mongo:
  url: mongodb://localhost:27017/admin