port: 3003
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: setting
  sslmode: disable
redis:
  addr: localhost:6379
  password: ""
  db: 0
kafka:
  enable: true
  brokers: ["localhost:9092"]
  topics: ["hros_setting_events"]
  group_id: "hros_setting_svc_group"
nats:
  addr: localhost:4222
mongo:
  url: mongodb://localhost:27017/admin